### PR TITLE
Sane error handling

### LINKED ISSUE #1: Sane error handling.
I'd like to be able to use this library to parse XML that may not be valid. The `Element::parse` method should return a `Result` instead of panicking on errors.

### PR DESCRIPTION
**Pull request by canndrew**
Fix #1

### CODE REVIEW

**Comment by eminence** [comment]
I did a quick skim of this, and it looks good.  Thanks!   I'll merge it once I'm back from traveling (today or tomorrow)

**Comment by eminence** [comment]
Since this changes the public API, let's bump the xmltree version from 0.2.1 to 0.3.  Can you make that change?

**Comment by canndrew** [comment]
Done and done :)

**Comment by eminence** [comment]
Merged, and published to crates.io.  Thanks!

**Pull request merged**
