### PR TITLE
Add support in Element for namespaces and prefixes

### PR DESCRIPTION
**Pull request by JoeyAcc**
The first couple of commits are not that interesting, mostly they deal with administrative stuff.
The last commit is noteworthy however: it adds support to the `Element` type for the `namespace` and a `prefix` fields, which I need for my project.

I'd much rather commit back than maintain a fork, so a merge would be much appreciated.

### CODE REVIEW

**Comment by eminence** [comment]
Hi!  Thanks for the PR.  Do you think you can only submit the namespace/prefix changes?  I'd like to keep that separate from the other changes.    Also, if you have any example files that use prefix/namespaces, that would be useful when adding new tests.

As for the other changes:
* I would prefer not to change the author section in Cargo.toml.  Instead I would like to create a new Contributors section in the readme, which will publicly acknowledge all of the contributors.
* There are for sure some formatting issues in this repo, but I not personally a fan of the 80-column limitation.   So I'll standardize on the default rustfmt rules, which are actually quite close to what you've proposed.

**Comment by JoeyAcc** [comment]
I'm willing to make the required changes, but I'm not sure how: github won't let me create a PR in which I cherrypick the commits, or if it does, it's well-hidden since I haven't found it yet.

I can live with the other bullet points BTW.

**Comment by eminence** [comment]
In github, a pull request is a request to merge 1 branch into another branch (not a request to merge some commits).  so you can update this PR by updated the branch in this PR.   For this reason, it's always recommended that PRs come from feature branches, not master branches (because rebasing or squashing or history editing a master branch isn't generally recommended)

So if you want to update this PR, please feel free.  but i'm also happy to cherry-pick your new feature and make the other changes myself.  just let me know what you'd like!

**Comment by eminence** [comment]
I cherry-picked in your namespace stuff as 3ebfb5f8f664b1d33b4fcb909fed0e811243259d and then made a few additional changes and test.  The formatting stuff I handled by running rustfmt (done in 51d4d73d867991f885c161a8c9222794ee4891ed).

So now that there is namespace support, I'm going to close this PR.  Thanks!

**Comment by JoeyAcc** [comment]
Hi, sorry about trailing off there. 
I got caught up with other job-related things that needed doing (as these things go). 
So thank you for picking up the slack :)

**Pull request closed without merging**
